// Contains path constants for application routes mapped to different roles.
export const ROUTES = {
  LOGIN: '/login',
  UNAUTHORIZED: '/unauthorized',
  SUPER_ADMIN: {
    HOMEPAGE: '/super-admin',
    DASHBOARD: '/super-admin/dashboard',
    TOWER: '/super-admin/tower',
    UNIT: '/super-admin/unit',
    FASILITAS: '/super-admin/fasilitas',
    PENGHUNI: '/super-admin/penghuni',
    ADMIN: '/super-admin/admin',
    VERIFIKASI: '/super-admin/verifikasi',
    ABSEN: '/super-admin/absen',
    LAPORAN: '/super-admin/laporan',
    GRAFIK: '/super-admin/grafik',
    AUDIT: '/super-admin/audit',
    INFORMASI: '/super-admin/informasi',
  },
  PEMELIHARAAN: {
    DASHBOARD: '/pemeliharaan/dashboard',
    TIKET: '/pemeliharaan/tiket',
    RIWAYAT: '/pemeliharaan/riwayat',
    CHAT: '/pemeliharaan/chat',
    ABSENSI: '/pemeliharaan/absensi',
  },
  KEUANGAN: {
    DASHBOARD: '/keuangan/dashboard',
    BILLING: '/keuangan/billing',
    RECONCILE: '/keuangan/reconcile',
    EXPENSE: '/keuangan/expense',
    REVENUE: '/keuangan/revenue',
    FACILITY: '/keuangan/facility',
    ABSEN: '/keuangan/absen',
    CHECKIN: '/keuangan/absensi-checkin',
  },
  KEBERSIHAN: {
    DASHBOARD: '/kebersihan/jadwal',
    JADWAL: '/kebersihan/jadwal',
    PERMINTAAN: '/kebersihan/permintaan',
    RIWAYAT: '/kebersihan/riwayat',
    ABSENSI: '/kebersihan/absensi',
    INFORMASI: '/kebersihan/informasi',
    CHECKIN: '/kebersihan/absensi-checkin',
  },
  KEAMANAN: {
    DASHBOARD: '/keamanan/dashboard',
    TAMU: '/keamanan/tamu',
    PARKIR: '/keamanan/parkir',
    BROADCAST: '/keamanan/broadcast',
    ABSENSI: '/keamanan/absensi',
  },
  FASILITAS: {
    DASHBOARD: '/fasilitas/dashboard',
    RESERVASI: '/fasilitas/reservasi',
    JADWAL: '/fasilitas/jadwal',
    KELOLA: '/fasilitas/kelola',
    TAGIHAN: '/fasilitas/tagihan',
    INFORMASI: '/fasilitas/informasi',
    CHECKIN: '/fasilitas/absensi-checkin',
  },
  PENGHUNI: {
    DASHBOARD: '/penghuni/beranda',
    BERANDA: '/penghuni/beranda',
    BILLING: '/penghuni/billing',
    LAPORAN: '/penghuni/laporan',
    PENGUMUMAN: '/penghuni/pengumuman',
    INFORMASI: '/penghuni/informasi',
    FASILITAS: '/penghuni/fasilitas',
    CS: '/penghuni/cs',
    PROFIL: '/penghuni/profil',
  }
};
