"""tambah tabel laporan insiden pemeliharaan

Revision ID: 0276584aed31
Revises: 734f87a04027
Create Date: 2026-05-23 01:26:27.106666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0276584aed31'
down_revision = '734f87a04027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('judul_laporan', sa.String(length=128), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=False),
    sa.Column('lokasi', sa.String(length=64), nullable=False),
    sa.Column('tingkat_darurat', sa.String(length=16), nullable=True),
    sa.Column('status_laporan', sa.String(length=32), nullable=True),
    sa.Column('waktu_lapor', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incidents')
    # ### end Alembic commands ###
