"""tambah tabel staff dan jadwal kerja

Revision ID: 734f87a04027
Revises: d9b5f3f3bcba
Create Date: 2026-05-23 01:15:35.798954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '734f87a04027'
down_revision = 'd9b5f3f3bcba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_staff', sa.String(length=64), nullable=False),
    sa.Column('posisi', sa.String(length=32), nullable=False),
    sa.Column('nomer_hp', sa.String(length=16), nullable=True),
    sa.Column('status_kerja', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jadwal_tugas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(length=64), nullable=False),
    sa.Column('hari_tugas', sa.String(length=16), nullable=False),
    sa.Column('shift', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staffs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jadwal_tugas')
    op.drop_table('staffs')
    # ### end Alembic commands ###
