"""tambah tabel fasilitas dan visitor

Revision ID: d9b5f3f3bcba
Revises: 68e5657fa4df
Create Date: 2026-05-23 01:05:21.044010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9b5f3f3bcba'
down_revision = '68e5657fa4df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fasilitas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_fasilitas', sa.String(length=64), nullable=False),
    sa.Column('kapasitas', sa.Integer(), nullable=True),
    sa.Column('status_fasilitas', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_tamu', sa.String(length=64), nullable=False),
    sa.Column('nomer_identitas', sa.String(length=32), nullable=True),
    sa.Column('unit_tujuan', sa.String(length=16), nullable=False),
    sa.Column('keperluan', sa.String(length=128), nullable=False),
    sa.Column('waktu_masuk', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservasis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fasilitas_id', sa.Integer(), nullable=False),
    sa.Column('tanggal_booking', sa.String(length=32), nullable=False),
    sa.Column('jam', sa.String(length=16), nullable=False),
    sa.Column('status_booking', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['fasilitas_id'], ['fasilitas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservasis')
    op.drop_table('visitors')
    op.drop_table('fasilitas')
    # ### end Alembic commands ###
